# -*- coding: utf-8 -*-
"""
@Time    : 2018/2/15 9:50
@Author  : Sunflower
@FileName: 389. Find the Difference.py
@Software: PyCharm
@Blog    ：http://blog.csdn.net/sunflower_kris/article/
"""
"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"
Output:
e

Explanation:
'e' is the letter that was added.
"""


class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        if set(t) == set(s):
            for item in set(s):
                if t.count(item) > s.count(item):
                    return item
        else:
            return "".join(set(t)-set(s))

S = Solution()
print(S.findTheDifference(s="a", t="aa"))
